/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.model_Login;
import model.model_Permissons;
import model.model_User;
import repo.repo_Admin;

/**
 *
 * @author CanhPC
 */
public class view_Admin extends javax.swing.JFrame {

    /**
     * Creates new form view_Admin
     */
    private repo_Admin repoAdm = new repo_Admin();
    private ArrayList<model_User> listUsers = null;
    private ArrayList<model_Login> listAccountUsers = null;
    private int add;
    private int remove;
    private int update;
    private int select = -1;

    public view_Admin() {
        initComponents();
        loadUser();
        loadAccount();
        this.setLocationRelativeTo(null);
    }

    public void loadUser() {
        listUsers = repoAdm.findAllUsers();
        DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
        model.setRowCount(0);

        for (model_User user : listUsers) {
            Object[] rows = {
                user.getId(),
                user.getUsername()
            };
            model.addRow(rows);
        }
    }

    public void loadAccount() {
        listAccountUsers = repoAdm.findAllAccountUsers();
        DefaultTableModel model = (DefaultTableModel) tblUpdate.getModel();
        model.setRowCount(0);

        for (model_Login listAccountUser : listAccountUsers) {
            Object[] rows = {
                listAccountUser.getUsername(),
                listAccountUser.getPassword()
            };
            model.addRow(rows);
        }
    }

    private void checkPermissons(String username) {
        model_Permissons permissions = repoAdm.checkPermissons(username);
        if (permissions != null) {
            add = permissions.getCan_add() == 1 ? 1 : 0;
            remove = permissions.getCan_remove() == 1 ? 1 : 0;
            update = permissions.getCan_update() == 1 ? 1 : 0;
        }
    }

    private void clear() {
        cbbAdd.setSelected(false);
        cbbRemove.setSelected(false);
        cbbUpdate.setSelected(false);
        lblPermissions.setText("Change permisson:");
    }

    private void checkEmpty() {
        JOptionPane.showMessageDialog(this, "Khong duoc de trong");
        return;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUpdate = new javax.swing.JTable();
        btnUpdateNow = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        lblPermissions = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        cbbAdd = new javax.swing.JCheckBox();
        cbbRemove = new javax.swing.JCheckBox();
        cbbUpdate = new javax.swing.JCheckBox();
        txtTK = new javax.swing.JTextField();
        txtMK = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblUpdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password"
            }
        ));
        tblUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUpdateMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUpdate);

        btnUpdateNow.setText("Update now");
        btnUpdateNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateNowActionPerformed(evt);
            }
        });

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username"
            }
        ));
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblUser);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        lblPermissions.setText("Change permisson:");

        jLabel2.setText("Change info user:");

        btnClear.setText("Clear all");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        cbbAdd.setText("Add");

        cbbRemove.setText("Remove");

        cbbUpdate.setText("Update");

        jLabel1.setText("MK");

        jLabel3.setText("TK");

        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnUpdateNow)
                        .addGap(133, 133, 133)
                        .addComponent(btnClear)
                        .addGap(0, 61, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(cbbAdd)
                        .addGap(85, 85, 85)
                        .addComponent(cbbRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbUpdate)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPermissions)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTK, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                            .addComponent(txtMK))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(25, 25, 25))))
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(lblPermissions)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbAdd)
                    .addComponent(cbbRemove)
                    .addComponent(cbbUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateNow)
                    .addComponent(btnClear))
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(427, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
        // TODO add your handling code here:
        select = tblUser.getSelectedRow();
        if (select == - 1) {
            return;
        }

        String username = tblUser.getValueAt(select, 1).toString();
        lblPermissions.setText("Change permisson " + username + ":");
        checkPermissons(username);

        cbbAdd.setSelected(false);
        cbbRemove.setSelected(false);
        cbbUpdate.setSelected(false);

        if (add == 1) {
            cbbAdd.setSelected(true);
        }
        if (remove == 1) {
            cbbRemove.setSelected(true);
        }
        if (update == 1)
            cbbUpdate.setSelected(true);
    }//GEN-LAST:event_tblUserMouseClicked

    private void btnUpdateNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateNowActionPerformed
        // TODO add your handling code here:
        String username = tblUser.getValueAt(select, 1).toString();

        int addUpdate = 0;
        int removeUpdate = 0;
        int updateUpdate = 0;

        if (cbbAdd.isSelected()) {
            addUpdate = 1;
        }
        if (cbbRemove.isSelected()) {
            removeUpdate = 1;
        }
        if (cbbUpdate.isSelected()) {
            updateUpdate = 1;
        }

        model_Permissons permissons = new model_Permissons(removeUpdate, updateUpdate, addUpdate);
        this.repoAdm.updatePermissons(username, permissons);
        JOptionPane.showMessageDialog(this, "Cap nhat thanh cong");
        this.loadUser();
        this.clear();
    }//GEN-LAST:event_btnUpdateNowActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        this.clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String tk = txtTK.getText().trim();
        String mk = txtMK.getText().trim();

        if (tk.isEmpty()) {
            checkEmpty();
        }

        if (mk.isEmpty()) {
            checkEmpty();
        }

        for (model_Login listAccountUser : listAccountUsers) {
            if (listAccountUser.getUsername().equalsIgnoreCase(tk)) {
                JOptionPane.showMessageDialog(this, "Da ton tai " + tk + "khong the them moi.");
                return;
            }
        }

        model_Login login = new model_Login(tk, mk);
        
        this.repoAdm.add(login);
        JOptionPane.showMessageDialog(this, "Add thanh cong");
        this.loadAccount();
        this.loadUser();
        this.clear();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String tk = txtTK.getText().trim();
        String mk = txtMK.getText().trim();

        if (tk.isEmpty()) {
            checkEmpty();
            return;
        }

        if (mk.isEmpty()) {
            checkEmpty();
            return;
        }

        boolean check = false;

        for (model_Login listAccountUser : listAccountUsers) {
            if (listAccountUser.getUsername().equalsIgnoreCase(tk)) {
                check = true;
                break;
            }
        }

        if (!check) {
            JOptionPane.showMessageDialog(this, "Khong tim thay tk " + tk + " de sua.");
            return;
        }

        model_Login login = new model_Login(tk, mk);
        this.repoAdm.update(login);
        this.loadAccount();
        JOptionPane.showMessageDialog(this, "Update thanh cong.");
        this.clear();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUpdateMouseClicked
        // TODO add your handling code here:
        int select2 = tblUpdate.getSelectedRow();
        if (select2 == - 1) {
            return;
        }

        String tk = tblUpdate.getValueAt(select2, 0).toString();
        String mk = tblUpdate.getValueAt(select2, 1).toString();

        txtTK.setText(tk);
        txtMK.setText(mk);
    }//GEN-LAST:event_tblUpdateMouseClicked

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int select3 = tblUpdate.getSelectedRow();
        String tk = null;

        if (select3 != -1) {
            tk = tblUpdate.getValueAt(select3, 0).toString();
        } else {
            tk = txtTK.getText().trim();

            if (tk.isEmpty()) {
                checkEmpty();
                return;
            }
        }

        if (tk != null) {
            int confirm = JOptionPane.showConfirmDialog(this, "Ban co chac chan xoa no khong?");
            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            this.repoAdm.remove(tk);
            JOptionPane.showMessageDialog(this, "Remove thanh cong");
            this.loadAccount();
            this.loadUser();
            this.clear();
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new view_Login().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateNow;
    private javax.swing.JCheckBox cbbAdd;
    private javax.swing.JCheckBox cbbRemove;
    private javax.swing.JCheckBox cbbUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPermissions;
    private javax.swing.JTable tblUpdate;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txtMK;
    private javax.swing.JTextField txtTK;
    // End of variables declaration//GEN-END:variables
}
